#!/bin/sh

#修改lan网口为eth1
uci -q set network.lan.device='eth1'
#修改默认wan口为eth0
uci -q set network.wan.device='eth0'
uci -q set network.wan6.device='eth0'
uci commit network

#修改默认主题为argon
uci -q set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

#修改默认系统设置
#修改时区
uci -q set system.@system[0].timezone='CST-8'
uci -q set system.@system[0].zonename='Asia/Shanghai'
#删除默认ntp服务器
uci -q delete system.ntp.server
#增加ntp服务器
uci -q add_list system.ntp.server=ntp.ntsc.ac.cn
uci -q add_list system.ntp.server=ntp.aliyun.com
uci -q add_list system.ntp.server=cn.ntp.org.cn
uci commit system

# root默认密码root
sed -i 's|^root:[^:]*:|root:$1$zIMgxsz9$tIl71DXbq00Tkjwk0jGVf.:|' /etc/shadow

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='v$(date +'%Y.%m')'" >> /etc/openwrt_release
sed -i '/DISTRIB_RELEASE/d' /etc/openwrt_release
echo "DISTRIB_RELEASE='v$(date +'%Y.%m.%d')'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Build by gnodgl '" >> /etc/openwrt_release

sed -i '/luciname/d' /usr/lib/lua/luci/version.lua
echo "luciname ='ImmortalWrt'" >> /usr/lib/lua/luci/version.lua
sed -i '/luciversion/d' /usr/lib/lua/luci/version.lua
echo "luciversion ='master'" >> /usr/lib/lua/luci/version.lua

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

chmod 0755 /etc/init.d/*

exit 0
